/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: amora (https://sketchfab.com/amora)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-roll-39dbf14a2ec84a2089ef4331cf38e292
Title: Earth roll
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export function Earth(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/earth.gltf')
  const { actions } = useAnimations(animations, group)
  const { camera } = useThree()
  camera.position.set(0,0,7)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="1db3f5d59802464cbb8312f98512915efbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="PM3D_Sphere3D1_4" rotation={[Math.PI, -Math.PI / 5, Math.PI]} scale={1000}>
                  <group name="PM3D_Sphere3D1_6" rotation={[Math.PI / 2, 0, 0]}>
                    <mesh name="PM3D_Sphere3D1_6_PM3D_Sphere3D1_6_0" geometry={nodes.PM3D_Sphere3D1_6_PM3D_Sphere3D1_6_0.geometry} material={materials.PM3D_Sphere3D1_6} />
                  </group>
                  <mesh name="PM3D_Sphere3D1_4_PM3D_Sphere3D1_4_0" geometry={nodes.PM3D_Sphere3D1_4_PM3D_Sphere3D1_4_0.geometry} material={materials.PM3D_Sphere3D1_4} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth.gltf')
