/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 clock.gltf 
Author: Egor Likhachev (https://sketchfab.com/egor_likhachev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-clock-0a564a419fac447ba4eb7c9db5e9ed39
Title: Table Clock
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export function Clock3d(props) {
  const { nodes, materials } = useGLTF("/models/clock.gltf");
  const { camera } = useThree()
  camera.position.set(0,1,1)
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Inner_body_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Dial_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Glass_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Body_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Back_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.DingDong_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Pipki_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Duga_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Legs_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Button_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Switch_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Lit_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Tumblers_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Hammer_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Hour_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Minute_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Bolt_Clock_0.geometry}
          material={materials.Clock}
          position={[0, 0.443, 0.013]}
          rotation={[-1.77, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/clock.gltf");
